name: Bug report
description: Report a bug.
title: "BUG: <Please replace this text with a comprehensive title>"

body:
- type: markdown
  attributes:
    value: >
      Thank you for taking the time to file a bug report. Before creating a new
      issue, please take a few minutes to try these steps:
      1) Check if the issue has already been brought up.
      2) Try upgrading to the latest version of Kilosort.
      3) Check relevant pages at kilosort.readthedocs.io

- type: markdown
  attributes:
    value: >
      If the bug occurred during sorting, please also upload the kilosort.log
      file located in the results directory (v4.0.8 or later).
    
- type: textarea
  attributes: 
    label: "Describe the issue:"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Reproduce the bug:"
    description: >
      A short code example that reproduces the problem/missing feature,
      if applicable.
    render: python
  
- type: textarea
  attributes:
    label: "Error message:"
    description: >
      Please include full error message, if any.
    render: shell

- type: textarea
  attributes:
    label: "Version information:"
    description: >
      Version of python, Kilosort, operating system, and any other
      software versions you think might be relevant to the bug (e.g. CUDA toolkit).
  validations:
    required: true

- type: textarea
  attributes:
    label: "Context for the issue:"
    description: |
      Please explain how this issue affects your work or why it should be prioritized.

- type: textarea
  attributes:
    label: "Experiment information:"
    description: >
      Type of probe used, species and brain area recorded from, etc, if your bug
      is related to "strange/unexpected results."
