name: Other issue
description: Report something about Kilosort.
title: "<Please replace this text with a comprehensive title>"

body:
    
- type: textarea
  attributes: 
    label: "Describe the issue:"
    description: >
      Description.
  validations:
    required: true  
